basket = {"orange", "apple", "apple", "pear", "orange", "banana"}
print(f"原集合是{basket}")
print(f"判断orange是否在集合中{'orange' in basket}")
print(f"判断呵呵是否在集合中{'呵呵' in basket}")

a = set('aabbcc')
b = set('ccddee')
print(f"集合a中不包含在集合b的结果集是{a - b}")
print(f"包含在集合a或者包含在集合b中的结果集是{a | b}")
print(f"包含在集合a且包含在集合b的结果集是{a & b}")
print(f"不同时包含于集合a集合b的结果集是{a ^ b}")
print(f"basket添加一个元素aa{basket.add('aa')},的结果是{basket}")
print(f"basket添加一组元素{basket.update({'cc','dd','ee'})}的结果是{basket}")
print(f"basket移除一个存在的元素{basket.remove('dd')}的结果是{basket}")
print(f"使用discard移除basket中的一个元素{basket.discard('dd')}即使元素不存在也不报错")
print(f"随机删除集合中的一个元素{basket.pop()}")
print(f"集合的长度是{len(basket)}")
print(f"清空集合中的元素{basket.clear()}")


c = set('aabbcc')
d = set('ccddee')
print(f"拷贝一个集合{c.copy()}")
print(f"集合c中不包含与集合d的元素{c.difference(d)}")
print(f"集合c中除了不包含与集合d中的元素外其他全部移除{c.difference_update(d)}{c}")
c = set('aabbcc')
print(f"集合c中包含于集合d中的元素{c.intersection()}")
print(f"集合c中除了包含于集合d中的元素外全部删除{c.intersection_update(d)}之后的结果集是{c}")
c = set('aabbcc')
print(f"集合c是否没有集合d有交集：{c.isdisjoint(d)}")
print(f"集合c是否是集合d的子集{c.issubset(d)}")
print(f"集合c是否是集合d的父集{c.issuperset(d)}")
print(f"集合c删除元素a{c.remove('a')}之后的结果集是{c}")
print(f"集合c随机删除元素{c.pop()}之后的结果集是{c}")
c = set('aabbcc')
print(f"集合c与集合d的差集是{c.symmetric_difference(d)}")
print(f"集合c中除了与集合d的差集以外全部移除，且将结合d中不包含与集合c中的元素插入到集合c中{c.symmetric_difference_update(d)}之后的结果集是{c}")
print(f"集合c与集合d的并集{c.union(d)}")
